### PR TITLE
add date string

### PR DESCRIPTION
**Pull request by Azuki-bar**
送信日時が欲しかったので追加しましたがデバッグは一切していないので任せます。

https://developers.google.com/apps-script/reference/utilities/utilities#formatdatedate,-timezone,-format

### CODE REVIEW

**Comment by otariidae** [comment]
Nice suggestion.
But I intended the text mimics the real mail format. How about changing the format to fit the specification?
`Date` field is defined at RFC5322 [section 3.6.1](https://datatracker.ietf.org/doc/html/rfc5322#section-3.6.1) and date-time       format is defined at [section 3.3](https://datatracker.ietf.org/doc/html/rfc5322#section-3.3). It should look like `Mon, 2 Jan 2006 15:04:05 -0700`.

**Comment by Azuki-bar** [comment]
that a good idea.
I will fix date format to fit RFC5322 section3.6.1.

**Comment by otariidae** [comment]
looks like you missed comma `,` after day-of-week
I committed to fix it

**Review by otariidae — APPROVED** [review]

**Comment by otariidae** [comment]
merged. huge thanks, @Azuki-bar

**Pull request merged**
